---
- hosts: default
  remote_user: vagrant
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest
      become: yes

    - name: Install dependencies required to setup a new version of Python
      yum: name=yum-utils state=latest
      become: yes
      
    - name: Install dependencies 
      sudo: yes
      yum: name=gcc state=latest
      become: yes

    - name: epel
      yum: name=epel-release state=latest
      become: yes

    - name: python34
      yum: name=python34 state=latest
      become: yes

    - name: pip3
      yum: name=python34-setuptools state=latest
      become: yes

    - name: pip
      yum: name=python-pip state=latest
      become: yes
      
    - name: "Install Python packages xlwt"
      yum: name=python-xlwt state=latest
      become: yes
 
    - name: "Install Python packages selenium"
      pip: name=selenium 
      become: yes

    - name: "Install Python pyvirtualdisplay"
      pip: name=pyvirtualdisplay #state=latest
      become: yes
    
    - name: "Install Python Xvfb"
      yum: name=Xvfb state=latest
      become: yes
    
    - name: Install unzip
      yum: name=unzip state=latest
      become: yes

    - name: Install tar
      yum: name=tar state=latest
      become: yes

    - name: Unarchive chromedriver
      unarchive:
        src: https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
        dest: /usr/bin
        remote_src: yes
      become: yes

    - name: Install csv
      yum: name=csv state=latest
      become: yes
    
    - name: Install vim
      yum: name=vim state=latest
      become: yes

    - name: Install Chrome
      yum: name=https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm 
      become: yes

    - name: Install dependencies required to setup a new version of Python
      pip: name={{ item }} state=latest
      tags: [packages]
      become: yes
      with_items:
        - beautifulsoup4
        - blinker
        - XlsxWriter
        - xlwt
        - slackclient
        - slacker
        - urllib3
        - selenium
        - html5lib
        - httplib2
        - lxml
        - pprint
        - requests
        - Pillow



